#ifndef CROP_H
#define CROP_H

char *CropParam[]={"TBASEM",
                   "TEFFMX",
		   "TSUMEM",
		   "IDSL",
                   "VERSAT",
                   "VBASE",
		   "TSUM1",
		   "TSUM2",
                   "DVSI",
		   "DVSEND",
		   "TDWI",
                   "RGRLAI",
                   "SPA",
                   "LAICR",
                   "TBASE",
		   "RDRL",
		   "RDRSHM",
		   "CFET",
		   "DEPNR",
		   "IAIRDU",
		   "RDI",
		   "RRI",
		   "RDMCR",
                   "DVSDR",
                   "DVSDLT",
                   "RDRLV_NPK",  
                   "DVS_NPK_STOP", 
                   "DVS_NPK_TRANSL",  
                   "N_TRANSLRT_FR",
                   "NCRIT_FR",      
                   "NMAXRT_FR",   
                   "NMAXST_FR",   
                   "NLAI_N",   
                   "NLUE_N",   
                   "NMAXSO", 
                   "NPART", 
                   "NSLA",   
                   "NRESIDLV",  
                   "NRESIDST",  
                   "NRESIDRT",    
                   "TCNT", 
                   "NFIXF",
                   "FRTRL",
                   "ISINK",
                   "PGRIG",
                   "GRMX",
                   "NUMGA",
                   "NUMGB",
                   "IHEAT",
                   "DVSHEB",
                   "DVSHEF",
                   "NULL"
		   };
		   
char *CropParam2[]={
                    "PHOTTB",
                    "VERNRT",
                    "DTSMTB",
                    "SLATB",
                    "SSATB",
                    "KDIFTB",
                    "RUETB",
		    "TMPFTB",
		    "TMNFTB",
                    "COTB",
		    "FRTB",
                    "FLTB",
                    "FSTB",
		    "FOTB",
		    "RDRLTB",
		    "RDRRTB",
                    "RDRSTB",
                    "NMAXLV_TB",
                    "TMGTB",
                    "RDGRTB",
                    "NULL"
		    };

extern void FillCropVariables();
extern int FillAfgenTables();
#endif	// CROP_H

