#ifndef CROP_H
#define CROP_H

char *CropParam[]={"TBASEM",
                   "TEFFMX",
		   "TSUMEM",
		   "IDSL",
                   "VERSAT",
                   "VBASE",
		   "TSUM1",
		   "TSUM2",
                   "DVSI",
		   "DVSEND",
		   "TDWI",
                   "RGRLAI",
                   "SPA",
                   "LAICR",
                   "TBASE",
		   "RDRL",
		   "RDRSHM",
		   "CFET",
		   "DEPNR",
		   "IAIRDU",
		   "RDI",
		   "RRI",
		   "RDMCR",
                   "DVSDR",
                   "DVSDLT",
                   "RDRNS",  
                   "DVSNLT", 
                   "DVSNT",  
                   "FNTRT",  
                   "FRNX",    
                   "LRNR",   
                   "LSNR",   
                   "NLAI",   
                   "NLUE",   
                   "NMAXSO",  
                   "NPART",  
                   "NSLA",   
                   "RNFST",  
                   "NRESIDST",  
                   "RNFRT",  
                   "TCNT",     
                   "NFIXF",
                   "FRTRL",
                   "ISINK",
                   "GRMX",
                   "NUMGA",
                   "NUMGB",
                   "IHEAT",
                   "DVSHEB",
                   "DVSHEF",
                   "NULL"
		   };
		   
char *CropParam2[]={
                    "PHOTTB",
                    "VERNRT",
                    "DTSMTB",
                    "SLATB",
                    "SSATB",
                    "KDIFTB",
                    "RUETB",
		    "TMPFTB",
		    "TMPFTB",
		    "TMNFTB",
                    "COTB",
		    "FRTB",
                    "FLTB",
                    "FSTB",
		    "FOTB",
		    "RDRLTB",
		    "RDRRTB",
                    "RDRSTB",
                    "NMXLV",
                    "TMGTB",
                    "RDGRTB",
                    "NULL"
		    };

extern void FillCropVariables();
extern int FillAfgenTables();
#endif	// CROP_H

